name: Codacy Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  codacy-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run Codacy Analysis
        run: |
          docker run --rm \
            -e CODACY_PROJECT_TOKEN=$CODACY_PROJECT_TOKEN \
            -v $(pwd):/src \
            codacy/codacy-analysis-cli analyze
